name: CI - Pipeline Informatif

on:
  push:
    branches:
      - lab-1


jobs:
  integration-continue:
    name: Démonstration CI
    runs-on: ubuntu-latest

    env:
      STEP1: "Le code vient d’être poussé sur GitHub"

    steps:
      - name: Étape 1 - Initialisation
        run: |
          echo "Démarrage du pipeline d’intégration continue"
          echo "STEP1= $STEP1"

      - name: Étape 2 - Récupération du code
        run: |
          echo "Récupération du code source"
          echo "STEP2= ${{ vars.STEP2 }}"

      - name: Étape 3 - Build
        run: |
          echo "Phase de build"
          echo  "${{ secrets.MY_SECRET }}"

      - name: Étape 4 - Tests
        run: |
          echo "Phase de tests"
          echo "Exécution des tests unitaires"
          echo "Vérification de la qualité du code"

      - name: Étape 5 - Packaging
        run: |
          echo "Phase de packaging"
          echo "Création d’un artefact ou d’une image Docker"

      - name: Étape 6 - Fin du pipeline
        run: |
          echo "Le pipeline CI s’est exécuté avec succès"
